from pathlib import Path

DATA_PATH = Path("data/")
OUT_PATH = Path("subs/")

HISTORICAL_LOGS_PATH = Path("data/historical_user_logs.csv")

#Location for saving intermediate files generated by code
SAVE_PATH = Path("utility/")

validation_flag = 1 #If 1 use last day for validation else use last 2 days